# Generated by Django 2.2.4 on 2019-09-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Onayla'),
        ),
    ]
