# Generated by Django 2.2.4 on 2019-09-03 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20190902_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Bu alana yalnızca harf ve boşluk karakteri girebilirsiniz (Max 25 karakter).', regex='^[a-zA-Z]ıİğĞüÜçÇöÖşŞ {2,25}$')], verbose_name='Şehir'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Bu alana yalnızca harf ve boşluk karakteri girebilirsiniz (Max 25 karakter).', regex='^[a-zA-Z]ıİğĞüÜçÇöÖşŞ {2,25}$')], verbose_name='Soyadı'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Bu alana yalnızca harf ve boşluk karakteri girebilirsiniz (Max 25 karakter).', regex='^[a-zA-Z]ıİğĞüÜçÇöÖşŞ {2,25}$')], verbose_name='Adı'),
        ),
    ]
