# Generated by Django 2.2.4 on 2019-09-03 22:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20190903_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencecode',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Bu alana yalnızca harf ve boşluk karakteri girebilirsiniz (Max 25 karakter).', regex='^[a-zA-ZıİğĞüÜçÇöÖşŞ ]{2,25}$')], verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='application',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Bu alana yalnızca harf ve boşluk karakteri girebilirsiniz (Max 25 karakter).', regex='^[a-zA-ZıİğĞüÜçÇöÖşŞ ]{2,25}$')], verbose_name='Soyadı'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Bu alana yalnızca harf ve boşluk karakteri girebilirsiniz (Max 25 karakter).', regex='^[a-zA-ZıİğĞüÜçÇöÖşŞ ]{2,25}$')], verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reference_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='apply.ReferenceCode', verbose_name='Referans Kodu'),
        ),
    ]
