# Generated by Django 2.2.4 on 2019-09-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_auto_20190903_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencecode',
            name='piece',
            field=models.SmallIntegerField(default=1, verbose_name='Adet'),
        ),
    ]
